create tablespace CAMPUS_DEV_DATA datafile 'C:\data\oracle11g\campus_dev_tablespace.dbf' size 100m;
create tablespace CAMPUS_TEST_DATA datafile 'C:\data\oracle11g\campus_test_tablespace.dbf' size 100m;
create user CAMPUS_DEV identified by CAMPUS_DEV
default tablespace CAMPUS_DEV_DATA;
grant dba to CAMPUS_DEV;
create user CAMPUS_TEST identified by CAMPUS_TEST
default tablespace CAMPUS_TEST_DATA;
grant dba to CAMPUS_TEST;

CREATE TABLE "CAMPUS_DEV"."ROOMS"
(
	"ID" NUMBER(19,0),
    "CAPACITY" NUMBER(10,0),
    "FLOOR" NUMBER(10,0),
    "ROOMNUMBER" VARCHAR2(255 CHAR),
    CONSTRAINT ROOM_PK PRIMARY KEY ("ID")
);

CREATE TABLE "CAMPUS_DEV"."PROFILES"
(
    "ID" NUMBER(19,0),
	"BIRTHDATE" DATE,
	"COURSE" NUMBER(10,0),
	"FACULTY" VARCHAR2(255 CHAR),
	"FIRSTNAME" VARCHAR2(255 CHAR),
	"GENDER" NUMBER(10,0),
	"GROUP_NUMBER" NUMBER(10,0),
	"LASTNAME" VARCHAR2(255 CHAR),
	"SPECIALITY" VARCHAR2(255 CHAR),
	"ROOM_ID" NUMBER(19,0),
    CONSTRAINT PROFILE_PK PRIMARY KEY ("ID"),
    CONSTRAINT FK_ROOM FOREIGN KEY ("ROOM_ID") REFERENCES "CAMPUS_DEV".ROOMS("ID")
);

CREATE TABLE "CAMPUS_TEST"."ROOMS"
(
	"ID" NUMBER(19,0),
    "CAPACITY" NUMBER(10,0),
    "FLOOR" NUMBER(10,0),
    "ROOMNUMBER" VARCHAR2(255 CHAR),
    CONSTRAINT ROOM_PK PRIMARY KEY ("ID")
);

CREATE TABLE "CAMPUS_TEST"."PROFILES"
(
    "ID" NUMBER(19,0),
	"BIRTHDATE" DATE,
	"COURSE" NUMBER(10,0),
	"FACULTY" VARCHAR2(255 CHAR),
	"FIRSTNAME" VARCHAR2(255 CHAR),
	"GENDER" NUMBER(10,0),
	"GROUP_NUMBER" NUMBER(10,0),
	"LASTNAME" VARCHAR2(255 CHAR),
	"SPECIALITY" VARCHAR2(255 CHAR),
	"ROOM_ID" NUMBER(19,0),
    CONSTRAINT PROFILE_PK PRIMARY KEY ("ID"),
    CONSTRAINT FK_ROOM FOREIGN KEY ("ROOM_ID") REFERENCES "CAMPUS_DEV".ROOMS("ID")
);