CREATE TABLE "ROOMS"
(
	"ID" NUMBER(19,0),
    "CAPACITY" NUMBER(10,0),
    "FLOOR" NUMBER(10,0),
    "ROOM_NUMBER" VARCHAR2(255 CHAR),
    CONSTRAINT ROOM_PK PRIMARY KEY ("ID")
);

CREATE TABLE "PROFILES"
(
    "ID" NUMBER(19,0),
	"FIRST_NAME" VARCHAR2(255 CHAR),
	"LAST_NAME" VARCHAR2(255 CHAR),
	"GENDER" NUMBER(10,0),
    "BIRTH_DATE" DATE,
	"FACULTY" VARCHAR2(255 CHAR),
	"SPECIALITY" VARCHAR2(255 CHAR),
	"COURSE" NUMBER(10,0),
	"GROUP_NUMBER" NUMBER(10,0),
	"IMAGE_PATH" VARCHAR2(255 CHAR),
	"ROOM_ID" NUMBER(19,0),
    CONSTRAINT PROFILE_PK PRIMARY KEY ("ID"),
    CONSTRAINT FK_ROOM FOREIGN KEY ("ROOM_ID") REFERENCES ROOMS("ID")
);