CREATE TABLE "ROOMS"
(
	"ID" NUMBER(19,0),
    "CAPACITY" NUMBER(10,0),
    "FLOOR" NUMBER(10,0),
    "ROOM_NUMBER" VARCHAR2(255 CHAR),
    CONSTRAINT ROOM_PK PRIMARY KEY ("ID")
);

CREATE TABLE "PROFILES"
(
    "ID" NUMBER(19,0),
	"FIRST_NAME" VARCHAR2(255 CHAR),
	"LAST_NAME" VARCHAR2(255 CHAR),
	"GENDER" NUMBER(10,0),
    "BIRTH_DATE" DATE,
	"FACULTY" VARCHAR2(255 CHAR),
	"SPECIALITY" VARCHAR2(255 CHAR),
	"COURSE" NUMBER(10,0),
	"GROUP_NUMBER" NUMBER(10,0),
	"IMAGE_PATH" VARCHAR2(255 CHAR),
	"ROOM_ID" NUMBER(19,0),
    CONSTRAINT PROFILE_PK PRIMARY KEY ("ID"),
    CONSTRAINT FK_ROOM FOREIGN KEY ("ROOM_ID") REFERENCES ROOMS("ID")
);

CREATE TABLE "CAMPUS_USERS"
(
    "ID" NUMBER(19,0),
	"LOGIN" VARCHAR2(255 CHAR),
	"PASSWORD" VARCHAR2(255 CHAR),
	"ROLE" NUMBER(10,0),
	"PROFILE_ID" NUMBER(19,0),
    CONSTRAINT USER_PK PRIMARY KEY ("ID"),
    CONSTRAINT FK_PROFILE FOREIGN KEY ("PROFILE_ID") REFERENCES PROFILES("ID")
);

CREATE TABLE "EVENTS"
(
    "ID" NUMBER(19,0),
	"TITLE" VARCHAR2(255 CHAR),
	"BODY" VARCHAR2(255 CHAR),
	"PROFILE_ID" NUMBER(19,0),
    CONSTRAINT EVENTS_PK PRIMARY KEY ("ID"),
    CONSTRAINT FK_EVENTS_PROFILE FOREIGN KEY ("PROFILE_ID") REFERENCES PROFILES("ID")
);

CREATE TABLE "LIKES"
(
	"LIKE_FROM" NUMBER(19,0),
	"LIKE_TO" NUMBER(19,0),
    "LIKE_TYPE" NUMBER(10,0)
);